parent_dir = "exp/abalone/tvae"
real_data_path = "data/abalone/"
seed = 0
device = "cuda:0"

[train_params]
lr = 1e-4
epochs = 300
embedding_dim = 64 # 128
batch_size = 128
loss_factor = 0.8306279147963365
compress_dims = [
    128,
    128,
]
decompress_dims = [
    128,
    128,
]

[sample]
seed = 0
num_samples = 2672

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[dp]
epsilon = "__none__" # 10  5  1
delta = 1e-5
max_grad_norm = 1
